### ISSUE TITLE
profile selector hard codes moderator types

### ISSUE THREAD

**Issue by michaelneale** [Kvadratni/goose-intellij#11]
so: 

```
block:
  provider: block
  processor: claude-3-5-sonnet-2
  accelerator: gpt-4o-mini
  moderator: synopsis
  toolkits:
    - name: synopsis
      requires: {}    
    - name: github
      requires: {}  
```

is a pretty good current config but it isn't supported as dropdown won't have synopsis for moderator (also accelerator isn't right either - as it doesn't have that claude model) - should these be hard coded or allow it to be dynamic/overridable?
